### ISSUE TITLE
conda and pip installs both error out for fiona

### ISSUE THREAD

**Issue by mhweber** [ramonprz/pycon21-dashboards-4-all#1]
@ramonprz01, I tried both your install methods (conda and pip) and both generated errors for installing fiona

**Comment by ramonprz01** [comment]
Thanks for letting me know @mhweber. I am looking into it and will update it shortly

**Comment by sfavorite** [comment]
I had no trouble installing the environment or fiona. 

OS: Ubuntu 20.10
Python: 3.9.4
Finoa: 1.8.18

**Comment by mhweber** [comment]
Thanks @sfavorite , @ramonprz01 - I created the environment from yaml file again this morning and no longer seem to be having issue with fiona - user error on my end!
