### ISSUE TITLE
Notebooks 

### ISSUE THREAD

**Issue by sfavorite** [ramonprz/pycon21-dashboards-4-all#2]
In the table of contents it lists multiple notebooks but the git repository only has '01 Static Dashboards'. I may be reading the directions wrong - if so my apologies. 

7. Notebooks
    00 Checking that we are ready to go - 
    01 Static Dashboards - 
    02 Interactive Dashboars [sic] - 
    03 Dashboard Deployment -

**Comment by ramonprz01** [comment]
Hi Scot. Thanks for the message. I will be adding the remaining notebooks shortly.
