### ISSUE TITLE
Data download link is broken or limited!

### ISSUE THREAD

**Issue by GmGniap** [ramonprz/pycon21-dashboards-4-all#3]
Hello Ramon , 
I'm just virtual learner from Burma and I found your tutorial through PyCon 21 public Youtube playlist. I tried to follow your tutorial and noticed that necessary data download link isn't active anymore. I'm really sorry if it's only limited for Conference time & participants , then don't mind this issue. If not , may I request the fresh data download link if possible. 

Really really appreciated your presentation and contribution. 
Regards ,

**Comment by ramonprz** [comment]
Hi @GmGniap. Thanks for letting me know. I've just updated the link to the data and you should be able to access it without any issues.

**Comment by GmGniap** [comment]
Thanks a lot @ramonprz , it's working now.
